// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "CatA.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

CatA::CatA() : Subsystem("CatA") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    catA1 = RobotMap::catACatA1;
    catA2 = RobotMap::catACatA2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
void CatA::init(){
	catA1->Enable();
	catA2->Enable();
	catA2->SetEncPosition(0);
}

/*void CatA::setPosition(int setpoint,float p,float i,float d,float f){

//	RobotMap::intakeEncoder->Reset();
	catA1->SetPID(p,i,d,f);
	catA2->SetPID(p,i,d,f);
	catA1->Enable();
	catA2->Enable();
	catA1->SetSetpoint(setpoint);
	catA2->SetSetpoint(setpoint);
}*/

void CatA::chivelDeFrise(){
	//catA2->Set(CatA::calculatePID(0,catA2->GetEncPosition(),.02,0,.08));   //1350, 480
	if (Robot::catA_Moving) {
		CatA::initPID(0, catA2->GetEncPosition());
	}
	catA2->Set(computePID(0, catA2->GetEncPosition(), .02, 0, .08, 0)); //need to test values
}
void CatA::portcollisInit(){
	catA2->Set(calculatePID(0,catA2->GetEncPosition(),.02,0,.08));

}
void CatA::portcollisLift(){
	catA2->Set(CatA::calculatePID(0,catA2->GetEncPosition(),.02,0,.08));
}

void CatA::lower() {
	catA1->Set(.5);
	catA2->Set(-.5);
}

void CatA::stop() {
	catA1->Set(0);
	catA2->Set(0);
}

/* double CatA::calculatePID(double setpoint, double current, double Kp, double Ki, double Kd){
	int dir = 1; //flip sign to change direction
	const float horPos = 282.5;
	double encoderAngle = (dir*horPos-current)*(3.1415/2)/(182.75);  //horizontal is 1350, vert is 480
	f = -.4*cos(encoderAngle);
//	return f;
	double dVal = 0;
	Ki = 0.0000;
	double iVal = previousIVal + (double)setpoint-(double)current;
	printf("IVal %f",iVal);
	if(previous != 0){
		dVal = ((double)current-(double)previous)*Kd;
//		printf("Dval %f",dVal);
	}
	previousIVal = iVal;
	previous = current;
	return (Kp*(setpoint-current) + f)+(iVal*Ki)+-dVal;

} */

void CatA::initPID(double setpoint, double encPos) {
	iTerm = 0;
	lastError = setpoint - encPos;
}
double CatA::computePID(double setpoint, double encPos, double kP, double kI, double kD, double decay) {
		double error = setpoint - encPos; //assuming 200 is where robot starts
        double pTerm = error * kP;
        iTerm = iTerm * decay + error * kI;
        double dTerm = (lastError - error) * kD;
        lastError = error;
        double power = pTerm + iTerm + dTerm;
        return power;
}

void CatA::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

