// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Intake.h"
#include "../RobotMap.h"
#include "../Robot.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Intake::Intake() : Subsystem("Intake") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    intakeSpinTalon1 = RobotMap::intakeintakeSpinTalon1;
    intakeSpinTalon2 = RobotMap::intakeintakeSpinTalon2;
    intakeRotateTalon1 = RobotMap::intakeintakeRotateTalon1;
    intakeRotateTalon2 = RobotMap::intakeintakeRotateTalon2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
//    intakeSpinTalon2->SetControlMode(CANSpeedController::kFollower);
//    intakeSpin
//    intakeRotateTalon2->SetControlMode(CANSpeedController::kFollower);
//    intakeRotateTalon2->Set(6);
    spinTalonRunning = false;

//    intakeRotateTalon2->SetControlMode(CANTalon::ControlMode::kFollower);
//    intakeRotateTalon2->Set(3);
//    intakeRotateTalon2->SetInverted(true);
}

void Intake::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Intake::takeBallIn(){
	intakeSpinTalon1->Set(-1);
	intakeSpinTalon2->Set(-1);
	spinTalonRunning = true;

//	intakeRotateTalon1->Set(-.4);
}
void Intake::takeBallIn2(){ //Deprecated
	intakeSpinTalon2->Set(-1);
	spinTalon2Running = true;
}
void Intake::stopSpinner(){
	intakeSpinTalon1->Set(0);
	intakeSpinTalon2->Set(0);
//	intakeRotateTalon2->Set(0);
	spinTalonRunning = false;

}
void Intake::stopSpinner2(){
	intakeSpinTalon2->Set(0); //deprecated
	spinTalon2Running = false;
}

void Intake::moveArm(float speed){
	intakeRotateTalon1->Set(speed);
//	intakeRotateTalon2->Set(speed);

}

bool Intake::spinnerIsRunning(){
	return spinTalonRunning;

}
bool Intake::spinner2IsRunning(){
	return spinTalon2Running;
}
void Intake::init(){
	intakeSpinTalon1->Enable();
	intakeSpinTalon2->Enable();
	intakeRotateTalon1->Enable();
	intakeRotateTalon2->Enable();
//	intakeRotateTalon2->SetControlMode(CANTalon::kFollower);
//	intakeRotateTalon2->Set(3); //slaved to rotatetalon1
	intakeSpinTalon1->Set(0);
	intakeSpinTalon2->Set(0);
	intakeRotateTalon1->Set(0);
	intakeRotateTalon2->Set(0);

}
void Intake::setPosition(int setpoint,float p,float i,float d,float f){

//	RobotMap::intakeEncoder->Reset();
	RobotMap::intakePID->SetPID(p,i,d,f);
	RobotMap::intakePID->Enable();
	RobotMap::intakePID->SetSetpoint(setpoint);
}
void Intake::grabBall(){
	intakeSpinTalon1->Set(.35);
	intakeSpinTalon2->Set(.7);
	intakeRotateTalon1->Set(Intake::calculatePID(920,RobotMap::intakePot->Get(),.33*.015,0,.33*.08));
	intakeRotateTalon2->Set(Intake::calculatePID(920,RobotMap::intakePot->Get(),.33*.015,0,.33*.08));
}
void Intake::holdBall(){
	intakeSpinTalon1->Set(0);
	intakeRotateTalon1->Set(Intake::calculatePID(720,RobotMap::intakePot->Get(),.33*.015,0,.33*.08));
	intakeRotateTalon2->Set(Intake::calculatePID(720,RobotMap::intakePot->Get(),.33*.015,0,.33*.08));
}
double Intake::calculatePID(double setpoint, double current, double Kp, double Ki, double Kd){
	double encoderAngle = (current-855)*(3.1415/2)/(72);
//	printf("encoder angle %f",encoderAngle);
	f =.15*sin(encoderAngle);

	double dVal = 0;
	Ki = 0.0000;
	double iVal = previousIVal + (double)setpoint-(double)current;
//	printf("IVal %f",iVal);
	if(previous != 0){
		dVal = ((double)current-(double)previous)*Kd;
//		printf("Dval %f",dVal);
	}
	previousIVal = iVal;
	previous = current;
//	return f;

	return (Kp*(setpoint-current) + f)+(iVal*Ki)+-dVal;

}
void Intake::loadingBall(double cycleStartTime){
	loadingball = true;
	Robot::shooter->testPID(11.75);
	if((Timer::GetFPGATimestamp()-6.50)<(double)cycleStartTime){
		intakeRotateTalon1->Set(0);
		intakeRotateTalon2->Set(0);
		intakeRotateTalon2->Set(-1);
	}
	else if((Timer::GetFPGATimestamp()-7.7)<(double)cycleStartTime){
		readyToShoot=true;
		loadingball = false;
		intakeSpinTalon1->Set(0);
		intakeSpinTalon2->Set(0);
		intakeRotateTalon2->Set(0);
		Robot::shooter->stopShooter();
		SmartDashboard::PutNumber("thing happened! ",cycleStartTime);
	}
}
void Intake::stopIntakeSpinners(){
	intakeSpinTalon1->Set(0);
	intakeSpinTalon2->Set(0);
}
//void Intake::spinBack(){

//}
