// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "autonCommand.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
autonCommand::autonCommand(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain.get());
	Requires(Robot::catA.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void autonCommand::Initialize() {
	firstTime=true;
	autonNumber = SmartDashboard::GetNumber("Auton Number: ",1);
}

// Called repeatedly when this Command is scheduled to run
void autonCommand::Execute() {
//	Robot::drivetrain->driveToAngle(-.3,0);
	if(firstTime){
		startTime = Timer::GetFPGATimestamp();
		firstTime = false;
	}
	switch(autonNumber){
	case 1:
		auton1();
		break;
	case 2:
		auton2();
		break;
	default:
		auton1();
	}

//	Robot::drivetrain->driveSRX3->Set(.3);
}

// Make this return true when this Command no longer needs to run execute()
bool autonCommand::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void autonCommand::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void autonCommand::Interrupted() {

}
void autonCommand::auton1(){
	if(Timer::GetFPGATimestamp()<startTime+3){
		Robot::drivetrain->getDrive()->ArcadeDrive(-.5,.03*RobotMap::ahrs->GetYaw());
		Robot::catA->lower();
	}
	else if(Timer::GetFPGATimestamp()<startTime+5){
		Robot::catA->stop();
		Robot::drivetrain->getDrive()->ArcadeDrive(-.8,.03*RobotMap::ahrs->GetYaw());
	}

	else {
		Robot::drivetrain->getDrive()->ArcadeDrive(-.5,.03*RobotMap::ahrs->GetYaw());
	}
}
void autonCommand::auton2(){
	//chivel de frise
}
void autonCommand::auton3(){

}
void autonCommand::auton4(){
}
