// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "autonCommand.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

autonCommand::autonCommand(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void autonCommand::Initialize() {
	autonNumber = SmartDashboard::GetNumber("Auton Number: ",1);

}

// Called repeatedly when this Command is scheduled to run
void autonCommand::Execute() {
	Robot::drivetrain->driveToAngle(-.5,0);
//	Robot::drivetrain->driveSRX3->Set(.3);
}

// Make this return true when this Command no longer needs to run execute()
bool autonCommand::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void autonCommand::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void autonCommand::Interrupted() {

}
void autonCommand::auton1(){
}
void autonCommand::auton2(){
}
void autonCommand::auton3(){

}
void autonCommand::auton4(){
}
